# Generated by Django 3.2.21 on 2023-10-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_location_userprofile_home_country'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='userprofile',
        #     name='slug',
        #     field=models.SlugField(blank=True, max_length=200, unique=True),
        # ),
    ]
