# Generated by Django 3.2.21 on 2023-10-12 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='isnstagram_profile',
            new_name='instagram_profile',
        ),
    ]
