# Generated by Django 3.2.21 on 2023-11-02 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_country_slug'),
        ('accounts', '0006_auto_20231013_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='home_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.country'),
        ),
    ]
