# Generated by Django 3.2.21 on 2023-10-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='country',
        ),
    ]
