# Generated by Django 3.2.21 on 2023-10-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20231015_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='area_sq_km',
        ),
        migrations.RemoveField(
            model_name='country',
            name='capital',
        ),
        migrations.RemoveField(
            model_name='country',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='country',
            name='currency_code',
        ),
        migrations.RemoveField(
            model_name='country',
            name='currency_name',
        ),
        migrations.RemoveField(
            model_name='country',
            name='equivalent_fips_code',
        ),
        migrations.RemoveField(
            model_name='country',
            name='fips',
        ),
        migrations.RemoveField(
            model_name='country',
            name='geonameid',
        ),
        migrations.RemoveField(
            model_name='country',
            name='iso',
        ),
        migrations.RemoveField(
            model_name='country',
            name='iso3',
        ),
        migrations.RemoveField(
            model_name='country',
            name='iso_numeric',
        ),
        migrations.RemoveField(
            model_name='country',
            name='neighbours',
        ),
        migrations.RemoveField(
            model_name='country',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='country',
            name='population',
        ),
        migrations.RemoveField(
            model_name='country',
            name='postal_code_format',
        ),
        migrations.RemoveField(
            model_name='country',
            name='postal_code_regex',
        ),
        migrations.RemoveField(
            model_name='country',
            name='tld',
        ),
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
