# Generated by Django 3.2.21 on 2023-10-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20231015_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='area_sq_km',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='currency_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='population',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
