# Generated by Django 3.2.21 on 2023-10-15 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20231015_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='area_sq_km',
        ),
        migrations.RemoveField(
            model_name='country',
            name='capital',
        ),
        migrations.RemoveField(
            model_name='country',
            name='currency_name',
        ),
    ]
