# Generated by Django 3.2.21 on 2023-10-16 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20231015_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='population',
        ),
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='country',
            name='fips',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='country',
            name='iso',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='country',
            name='iso3',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='country',
            name='iso_numeric',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.country'),
        ),
    ]
