# Generated by Django 3.2.21 on 2023-10-16 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20231016_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='country',
            name='currency_code',
        ),
        migrations.RemoveField(
            model_name='country',
            name='currency_name',
        ),
        migrations.RemoveField(
            model_name='country',
            name='geonameid',
        ),
        migrations.RemoveField(
            model_name='country',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='country',
            name='neighbours',
        ),
        migrations.RemoveField(
            model_name='country',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='country',
            name='population',
        ),
        migrations.RemoveField(
            model_name='country',
            name='postal_code_format',
        ),
        migrations.RemoveField(
            model_name='country',
            name='postal_code_regex',
        ),
        migrations.RemoveField(
            model_name='country',
            name='tld',
        ),
    ]
