# Generated by Django 3.2.21 on 2023-10-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20231016_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='languages',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='country',
            name='neighbours',
            field=models.CharField(default='', max_length=100),
        ),
    ]
