# Generated by Django 3.2.21 on 2023-10-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20231016_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='country',
            name='postal_code_format',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='country',
            name='postal_code_regex',
            field=models.CharField(default='', max_length=100),
        ),
    ]
